set_property IOSTANDARD LVCMOS33 [get_ports CLK]
set_property IOSTANDARD LVCMOS33 [get_ports hitA]
set_property IOSTANDARD LVCMOS33 [get_ports hitB]
set_property IOSTANDARD LVCMOS33 [get_ports speedB]
set_property IOSTANDARD LVCMOS33 [get_ports speedA]
set_property PACKAGE_PIN P17 [get_ports CLK]
set_property PACKAGE_PIN P5 [get_ports hitA]
set_property PACKAGE_PIN R1 [get_ports hitB]
set_property PACKAGE_PIN P4 [get_ports speedA]
set_property PACKAGE_PIN N4 [get_ports speedB]

set_property PACKAGE_PIN F6 [get_ports testOut]
set_property IOSTANDARD LVCMOS33 [get_ports testOut]
